apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: springboot-demo
spec:
  type: NodePort
  ports:
    - port: 6380
      targetPort: 8080
  selector:
    app: springboot-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: springboot-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot-demo
          image: lucas2010/springboot-demo:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - springboot-demo
                topologyKey: "kubernetes.io/hostname"